config/routes.rb
Tasklistbdd::Application.routes.draw do
  resources :buckets, :shallow=>true do
    resources :tasks
  end
end

app/models/bucket.rb
class Bucket < ActiveRecord::Base
  has_many :tasks
end

app/models/task.rb
class Task < ActiveRecord::Base
  belongs_to :bucket
  scope :pending, where(["done=? or done isnull",false])
  scope :done, where(:done=>true)
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/buckets_controller.rb
class BucketsController < ApplicationController
  def index
    @buckets = Bucket.all
  end
  def new
    @bucket = Bucket.new
  end
  def create
    @bucket = Bucket.new(params[:bucket])
    if(@bucket.save)
      redirect_to buckets_path, :notice=>"Bucket created successfully"
    else
      render :action=>:new
    end
  end
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
  def index
    @bucket=Bucket.find(params[:bucket_id])
    @pending= @bucket.tasks.pending
    @done = @bucket.tasks.done
  end
  def new
    @bucket=Bucket.find(params[:bucket_id])
    @task = @bucket.tasks.build
  end
  def create
    @bucket=Bucket.find(params[:bucket_id])
    @task = Task.new(params[:task])
    @task.bucket = @bucket
    if(@task.save)
      redirect_to bucket_tasks_path(@bucket), :notice=>"Task created succesfully"
    else
      render :action=>:new
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/buckets_helper.rb
module BucketsHelper
end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/views/buckets/index.html.erb
<ul class="buckets">
  <% @buckets.each do |bucket| %>
    <li><%=link_to bucket.name, bucket_tasks_path(bucket)%></li>
  <% end %>
</ul>
<%=link_to 'New Bucket', new_bucket_path%>

app/views/buckets/new.html.erb
<%= semantic_form_for @bucket do |f| %>
  <%=f.inputs %>
  <%=f.buttons %>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Tasklistbdd</title>
  <%= stylesheet_link_tag :all %>
  <%= javascript_include_tag :defaults %>
  <%= csrf_meta_tag %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/tasks/index.html.erb
<ul id="pending">
  <% @pending.each do |task| %>
    <li><%=task.title%></li>
  <% end %>
</ul>
<ul id="done">
  <% @done.each do |task| %>
    <li><%=task.title%></li>
  <% end %>
</ul>
<%=link_to 'New Task', new_bucket_task_path(@bucket)%>

app/views/tasks/new.html.erb
<%= semantic_form_for [@bucket,@task] do |f| %>
  <%= f.inputs :title %>
  <%= f.buttons %>
<% end %>